apiVersion: apps/v1
kind: Deployment
metadata:
  name: ballonapp
  labels:
    app: ballonapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ballonapp
  template:
    metadata:
      labels:
        app: ballonapp
    spec:
      containers:
        - name: Ballonappcontainer
          image: balloncontainer.azurecr.io/:latest
           ports:
            - containerPort: 80