apiVersion: apps/v1
kind: Deployment
metadata:
  name: ballonapp
  labels:
    app: ballonapp
spec:
  replicas: 2  # Number of pod replicas
  selector:
    matchLabels:
      app: ballonapp
  template:
    metadata:
      labels:
        app: ballonapp
    spec:
    containers:
          - name: Ballonappcontainer
            image: balloncontainer.azurecr.io/:latest  # Replace with your Docker image
            ports:
            - containerPort: 80  # Port that your HTML/JS app serves on