apiVersion: v1
kind: Service
metadata:
  name: ballonapp-service
spec:
  selector:
    app: ballonapp-app
  ports:
    - protocol: TCP
      port: 80  # Service port
      targetPort: 80  # Container port
  type: LoadBalancer  # For external access
